### ISSUE TITLE
Tips 번역

### ISSUE THREAD

**Issue by dittos** [reactkr/react#50]
https://github.com/reactkr/react

저장소를 fork하여 'translation' 브랜치로 PR을 넣어주시면 됩니다. 이 이슈에서는 `docs/tips` 안의 문서를 번역합니다.
### 규칙
1. `translation` 브랜치는 원본을 유지하기 위해서 계속적으로 리베이스할 예정입니다. (적어도 일주일에 한번) 따라서 커밋에 **번역하는 원본의 커밋해시를 적어주셔야 합니다.**
2. **작업을 시작하시기 전에 댓글로 어느 부분을 번역하실지 알려주세요. 번역 진행이 겹치지 않기 위해서입니다.**
3. **머지가 먼저 되는 것이 우선적으로 적용됩니다.** 겹칠 경우 별도의 수정 PR을 보내주시기 바랍니다.
4. https://github.com/reactkr/react/wiki/Glossary 에 용어 번역들을 써 놓도록 합시다.
5. **기존 파일을 수정하는 것이 아니라** `ID.ko-KR.md` 형식의 파일을 새로 만들어주세요. (예: `thinking-in-react.md` -> `thinking-in-react.ko-KR.md
   `)
6. 문서 헤더의 id 필드는 `ID-ko-KR` 형식으로, permalink 필드는 `ID-ko-KR.html` 형식으로 적어주세요. 실제 HTML 파일은 permalink를 기준으로 생성되므로 prev, next 필드 및 문서 내용의 링크 또한 `ID-ko-KR.html`으로 걸어야 합니다.
7. 번역은 진행중인 리뷰가 없을 경우 리뷰어 2명 이상의 동의로 머지할 수 있습니다. 리뷰해주시는 분은 리뷰가 끝났다는 걸 알려주셔야 합니다.
### TODO
- [x] 01-introduction.md - @dittos
- [x] 02-inline-styles.md - @dittos
- [x] 03-if-else-in-JSX.md - @dittos
- [x] 04-self-closing-tag.md - @dittos
- [x] 05-maximum-number-of-jsx-root-nodes.md - @jiyeonseo 
- [x] 06-style-props-value-px.md - @jiyeonseo 
- [x] 07-children-props-type.md - @jiyeonseo 
- [x] 08-controlled-input-null-value.md - @jiyeonseo 
- [x] 09-componentWillReceiveProps-not-triggered-after-mounting.md - @jiyeonseo 
- [x] 10-props-in-getInitialState-as-anti-pattern.md - @jiyeonseo 
- [x] 11-dom-event-listeners.md - @dalinaum 
- [x] 12-initial-ajax.md - @dalinaum 
- [x] 13-false-in-jsx.md - @dalinaum 
- [x] 14-communicate-between-components.md - @arkist
- [x] 15-expose-component-functions.md - @arkist
- [x] 16-references-to-components.md - @arkist
- [x] 17-children-undefined.md - @arkist
- [x] 18-use-react-with-other-libraries.md - @arkist
- [x] 19-dangerously-set-inner-html.md - @dalinaum

**Comment by arkist** [comment]
14~18은 제가 하겠습니다

**Comment by jiyeonseo** [comment]
05~10 까지 해보겠습니다 :)

**Comment by dalinaum** [comment]
11~13 제가 할께요.

**Comment by dalinaum** [comment]
19번의 이름이 바뀌었습니다.
https://github.com/facebook/react/commit/2e1ccae2758e61ab86bc79bdcac0d61747065a4a

**Comment by marocchino** [comment]
반영해 두었습니다.

**Comment by dalinaum** [comment]
`19-dangerously-set-inner-html.md` 으로 변경되었습니다.

**Comment by marocchino** [comment]
헙.. 넵.

**Comment by dalinaum** [comment]
19번 맡는 사람없나요? 그럼 제가 맡겠습니다.

**Comment by dalinaum** [comment]
이 이슈를 닫읍시다.

**Comment by arkist** [comment]
고생하셨습니다!
